title: Creative Code Stammtisch
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A monthly open conversation between artists, 
  makers, designers, coders, performers, learners and anyone interested in the 
  use of computing skills for artistic expression.
baseurl: "/Stammtisch" # the subpath of your site, e.g. /blog
url: "https://creativecodeberlin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
kramdown:
  input: GFM
  hard_wrap: true

